version: '3'

networks:
  shared_network:
    external: true

services:
  order-service:
    build: ./burgernaut-order-service
    container_name: order-service
    ports:
    - "3000:3000"
    environment:
    - MONGODB_URI=mongodb://mongo:27017/orderdb
    - RABBITMQ_URL=amqp://user:password@rabbitmq
    - PORT=3000
    networks:
    - shared_network

  restaurant-service:
    build: ./restaurant-service
    container_name: restaurant-service
    ports:
    - "4000:4000"
    environment:
    - MONGODB_URI=mongodb://mongo:27017/orderdb
    - RABBITMQ_URL=amqp://user:password@rabbitmq
    - PORT=4000
    networks:
    - shared_network

  email-service:
    build: ./email-service
    container_name: email-service
    ports:
    - "5000:5000"
    environment:
    - RABBITMQ_URL=amqp://user:password@rabbitmq
    - EMAIL_USER=galadon110@gmail.com
    - EMAIL_PASS=vrge kxpm lrwe grcj
    - PORT=5000
    networks:
    - shared_network
